SET SERVEROUTPUT ON;
DECLARE
	V_BALANCE NUMBER(8);
BEGIN
	SELECT BALANCE INTO V_BALANCE FROM BANKDATA
	WHERE AGE = 75;
	DBMS_OUTPUT.PUT_LINE(V_BALANCE);
END;
/
DECLARE 
	V_BALANCE NUMBER(10);
	V_AGE NUMBER(5);
BEGIN
	SELECT AGE,BALANCE INTO V_AGE,V_BALANCE FROM BANKDATA
	WHERE AGE = 75;
	DBMS_OUTPUT.PUT_LINE(V_BALANCE || ' IS NOT OK FOR ' || V_AGE);
END;
/
