--anchored data type
SET ENVIRONMENT ON;
DECLARE
	V_AGE BANKDATA.AGE%TYPE;
BEGIN
	SELECT AGE INTO V_AGE FROM BANKDATA WHERE AGE=75;
	DBMS_OUTPUT.PUT_LINE(V_AGE);
END;
/
--without anchored datatype
DECLARE
        V_AGE NUMBER(8);
BEGIN
        SELECT AGE INTO V_AGE FROM BANKDATA WHERE AGE=75;
        DBMS_OUTPUT.PUT_LINE(V_AGE);
END;
